# Generated by Django 2.2.6 on 2019-10-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Nome',
            new_name='nome',
        ),
    ]
