# Generated by Django 2.2.6 on 2019-10-21 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultorio', '0003_auto_20191021_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
