# Generated by Django 2.2.6 on 2019-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0004_auto_20191021_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dt_consulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
